CREATE TABLE users(
    id GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username VARCHAR(200) NOT NULL ,
    email VARCHAR(200) UNIQUE NOT NULL ,
    password_hash VARCHAR(200) NOT NULL,
    email_verified BOOLEAN
);